### ISSUE TITLE
Random number seed setter

### ISSUE THREAD

**Issue by RyuMaster** [xaya/taurion_gsp#61]
In order to unit-test front-end properly, there needs to be a way to make sure, that random number generator always produces same numbers for the same moves both on mainnet and regtest. Hence, we need a way to manually feed seed into mainnet generator, and then use same for the regtest, which will make them identical

**Comment by domob1812** [comment]
Why do you need this?  That's somewhat hard, because the RNG is seeded based on the block hashes.  We could introduce some way to control this with e.g. command-line flags, but that then seems like a risk since people could accidentally get out of sync with everyone else by using those.  (Or someone with malicious intents could convince people who do not know what they are doing to set those flags.)

**Comment by RyuMaster** [comment]
Hmmmmm. I am just looking or an easy way to make front-end unit testing, but if that bring such complications, let it be then

**Comment by domob1812** [comment]
Yes sure, but I don't understand for what exactly you need this RNG seeding change.  If mainnet contains "enough complicated" behaviour to test the frontend, just let it sync to the actual mainnet chain block by block (e.g. using `invalidateblock` and `reconsiderblock`) to test the frontend.

Otherwise, you could just create a script that creates some situations you want to test on regtest similar to our integration tests for the GSP, for which you don't need a particular RNG seed.
